### ISSUE TITLE
Fix for missed key presses with raylib v3

### ISSUE THREAD

**Issue by frithrah** [oswjk/imgui-impl-raylib#1]
Thank you for putting this together Oskari.

Just a note for anyone using this with raylib v3. Keyboard handling has changed so you need to remove the additional call in ImGui_ImplRaylib_ProcessEvent otherwise you'll miss key presses occasionally. The fixed function should look like this:

	bool ImGui_ImplRaylib_ProcessEvent()
	{
		ImGuiIO &io = ImGui::GetIO();

		FOR_ALL_KEYS(SET_KEY_DOWN);

		io.AddInputCharacter(GetKeyPressed());

		return true;
	}

**Comment by oskaritimperi** [comment]
Thanks. I've commented out the call to `GetKeyPressed()` with a note if someone uses with v2.
