### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by ghost** [oswjk/imgui-impl-raylib#2]
Hello Oskari!

I see that your code follows the one of user [WEREMSOFT](https://github.com/WEREMSOFT) here on github.
Their license allows everyone to use the souce code in any way they wish. Does your code follow the same licensing pattern?

Thanks for putting this lib together by the way! I had an incredibly hard time trying to update the original code to work with raylib v3, and got no real success, but yours worked flawlessly! :D

**Comment by oskaritimperi** [comment]
Hmm. IIRC I wrote this piece of software from scratch. Probably looked for inspiration in the ImGui examples about GLFW etc. I could be wrong of course, I don't recall any details about this :-). WEREMSOFT repository seems to be newer than mine, not sure if that accounts for anything...

I've added the MIT license to the repo. Though that might be a bit overkill. :-)
